services:
  frontend:
    build:
      context: . # Project root
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "4200:4200"
    restart: unless-stopped
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - .env

  database:
    image: mariadb:10.6
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - "./database/data:/var/lib/mysql"
      - "./database/db_schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    env_file:
      - .env
